version: '3.8'

services:
  projecta:
    image: ghcr.io/skyapmtest/projecta
    environment:
      SW_AGENT_NAME: projectA

  projectb:
    image: ghcr.io/skyapmtest/projectb
    environment:
      SW_AGENT_NAME: projectB

  projectc:
    image: ghcr.io/skyapmtest/projectc
    environment:
      SW_AGENT_NAME: projectC
