---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: project-a
  name: project-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-a
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: project-a
    spec:
      containers:
        - image: ghcr.io/skyapmtest/projecta
          name: projecta
          ports:
            - containerPort: 8764
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: skywalking-oap:11800
            - name: SW_AGENT_NAME
              value: projectA
          resources: { }
status: { }
---
apiVersion: v1
kind: Service
metadata:
  name: project-a
spec:
  type: ClusterIP
  selector:
    app: project-a
  ports:
    - name: http
      port: 80
      targetPort: 8764

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: project-b
  name: project-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-b
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: project-b
    spec:
      containers:
        - image: ghcr.io/skyapmtest/projectb
          name: projectb
          ports:
            - containerPort: 8762
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: skywalking-oap:11800
            - name: SW_AGENT_NAME
              value: projectB
          resources: { }
status: { }
---
apiVersion: v1
kind: Service
metadata:
  name: project-b
spec:
  type: ClusterIP
  selector:
    app: project-b
  ports:
    - name: http
      port: 80
      targetPort: 8762

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: project-c
  name: project-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-c
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: project-c
    spec:
      containers:
        - image: ghcr.io/skyapmtest/projectc
          name: projectc
          ports:
            - containerPort: 8763
          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: skywalking-oap:11800
            - name: SW_AGENT_NAME
              value: projectC
          resources: { }
status: { }
---
apiVersion: v1
kind: Service
metadata:
  name: project-c
spec:
  type: ClusterIP
  selector:
    app: project-c
  ports:
    - name: http
      port: 80
      targetPort: 8763

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: project-d
  name: project-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-d
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: project-d
    spec:
      containers:
        - image: ghcr.io/skyapmtest/projectd
          name: projectd
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: skywalking-oap:11800
            - name: SW_AGENT_NAME
              value: projectD
            - name: BOOTSTRAP_SERVERS
              value: kafka:9092
          resources: { }
status: { }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper
    spec:
      containers:
        - image: zookeeper:3.4
          name: zookeeper
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          resources: { }
status: { }
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
    spec:
      containers:
        - image: bitnami/kafka:2.4.1
          name: kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_BROKER_ID
              value: "10"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          resources: { }
status: { }
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficgenerator
  labels:
    app: trafficgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficgenerator
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: trafficgenerator
    spec:
      containers:
        - name: trafficgenerator
          image: appropriate/curl
          args:
            - /bin/sh
            - -c
            - |
              while :; do
                curl http://project-a/projectA/test
                sleep 1
              done
---
apiVersion: v1
kind: Service
metadata:
  name: trafficgenerator
  labels:
    app: trafficgenerator
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: trafficgenerator
